import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";

import NavBar from '@/ui/NavBar/NavBar';


import { Inter } from "next/font/google";


// Récupère les infos de l'utilisateur connecté
import { getInfoUserAction } from "@/actions/auth.action";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  async function RootLayout({ children }) {

    // Récupère l'utilisateur connecté grâce au cookie/token
  const userConnected = await getInfoUserAction();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-row">
        <NavBar userConnected={userConnected} ></NavBar>

        <main className="flex-1">
        {children}
        </main>
      </body>
    </html>
  );
}
